# Generated by Django 5.2 on 2025-05-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_grade_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='comment',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
